### ISSUE TITLE
Connection error with `create_engine()`

### ISSUE THREAD

**Issue by flaneur2020** [databendlabs/databend-sqlalchemy#53]
```
Cleaning existing data...
Traceback (most recent call last):
  File "/Users/yazhou/code/databend-cloud/scripts/avia-regression-test/gendata.py", line 292, in <module>
    main()
  File "/Users/yazhou/code/databend-cloud/scripts/avia-regression-test/gendata.py", line 272, in main
    generator.clean_tables()
  File "/Users/yazhou/code/databend-cloud/scripts/avia-regression-test/gendata.py", line 53, in clean_tables
    conn.execute(text(query))
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1200, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 313, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1389, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1933, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 681, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/yazhou/.pyenv/versions/3.9.5/lib/python3.9/site-packages/databend_sqlalchemy/connector.py", line 182, in execute
    rows = self._db.query_iter(operation)
Exception: APIError: RequestError: Start Query failed with status 400 Bad Request: {"error":{"kind":"BadWarehouse","message":"no available endpoints with label [warehouse:tn59xeb01-bireportsecurerue-131790adea tenant:tn59xeb01]: Bad warehouse: warehouse tn59xeb01 bireport?secure=True not found"}}
```

my code:

```
from sqlalchemy import create_engine, text
self.engine = create_engine(connection_string)
```

conn string:

```
databend://cloudapp:{mypassword}@tn59xeb01.gw.aws-us-east-2.default.databend.com:443/default?warehouse=bireport&secure=True
```

version:

```
>>> import databend_sqlalchemy
>>> databend_sqlalchemy.__version__
'0.4.4'
```

**Comment by hantmac** [comment]
```
from sqlalchemy import create_engine, text
engine = create_engine("databend://cloudapp:[password]@host.databend.com:443?warehouse=test-sjh")
conn = engine.connect()
r = conn.execute("select 1")
r.fetchall()
```

**Comment by hantmac** [comment]
@flaneur2020 From v0.4.0 we use databend python Rust Binding as default driver, so the default ssl is true, no need to `secure=True`.
